# Importing Modules and Checking Directory

In [1]:
import os
import pandas as pd
import datetime
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
pd.__version__

'1.1.5'

In [3]:
os.getcwd()

'/Users/Livi/Projects/Black_mental_health/notebooks/Data_wrangling'

# Uploading Data

In [37]:
med = pd.read_csv("../../data/processed/final2016MEDICARE.csv", index_col=0, dtype={'full_zip':'str', 'npi':'str'})

In [38]:
med.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1047652 entries, 0 to 1047651
Data columns (total 22 columns):
 #   Column                               Non-Null Count    Dtype
---  ------                               --------------    -----
 0   npi                                  1047652 non-null  object
 1   entity_code                          1047652 non-null  object
 2   full_zip                             1047652 non-null  object
 3   state                                1047652 non-null  object
 4   country                              1047652 non-null  object
 5   provider_type                        1047652 non-null  object
 6   medicare_participation_indicator     1047652 non-null  object
 7   number_of_hcpcs                      1047652 non-null  int64
 8   number_of_services                   1047652 non-null  float64
 9   total_beneficiaries                  1047652 non-null  int64
 10  total_submitted_charges              1047652 non-null  float64
 11  total_allowed_payment                1047652 non-null  float64
 12  total_medicare_payment               1047652 non-null  float64
 13  total_medicare_standardized_payment  1047652 non-null  float64
 14  avg_beneficiary_age                  1047652 non-null  int64
 15  avg_hcc_risk_score                   1047652 non-null  float64
 16  services_per_capita                  1047652 non-null  float64
 17  allowed_payment_per_capita           1047652 non-null  float64
 18  medicare_payment_per_capita          1047652 non-null  float64
 19  submitted_charges_per_capita         1047652 non-null  float64
 20  region                               1047652 non-null  object
 21  subregion                            1047652 non-null  object
dtypes: float64(10), int64(3), object(9)
memory usage: 183.8+ MB

In [39]:
med.head()

,npi,entity_code,full_zip,state,country,provider_type,medicare_participation_indicator,number_of_hcpcs,number_of_services,total_beneficiaries,...,total_medicare_payment,total_medicare_standardized_payment,avg_beneficiary_age,avg_hcc_risk_score,services_per_capita,allowed_payment_per_capita,medicare_payment_per_capita,submitted_charges_per_capita,region,subregion
0,1003000126,I,21502,MD,US,Internal Medicine,Y,23,1477.0,518,...,124795.99,126129.38,75,2.0239,2.85,308.80,240.92,1441.18,South,South Atlantic
1,1003006586,I,20832,MD,US,Internal Medicine,Y,14,1583.0,579,...,126127.61,115349.97,80,2.3114,2.73,283.82,217.84,523.66,South,South Atlantic
2,1003006800,I,21202,MD,US,Physician Assistant,Y,16,81.0,69,...,10454.18,7630.64,70,1.0178,1.17,193.25,151.51,529.81,South,South Atlantic
3,1003007816,I,20910,MD,US,Ophthalmology,Y,35,2767.0,665,...,218768.39,195641.00,79,1.3003,4.16,453.27,328.98,792.66,South,South Atlantic
4,1003007824,I,21201,MD,US,Internal Medicine,Y,21,181.0,72,...,8591.92,7943.64,64,1.5482,2.51,153.66,119.33,230.89,South,South Atlantic

Checkpoint 1

In [40]:
checkpoint1 = med.copy()

In [41]:
pd.options.display.max_rows = 100
pd.options.display.max_colwidth = 100

In [42]:
census = pd.read_csv('../../data/raw/2016acs.csv')

In [43]:
census.head()

,geo_id,nonfamily_households,family_households,median_year_structure_built,rent_burden_not_computed,rent_over_50_percent,rent_40_to_50_percent,rent_35_to_40_percent,rent_30_to_35_percent,rent_25_to_30_percent,...,pop_5_years_over,speak_only_english_at_home,speak_spanish_at_home,speak_spanish_at_home_low_english,pop_15_and_over,pop_never_married,pop_now_married,pop_separated,pop_widowed,pop_divorced
0,61112,95,0,2002.0,0,56,10,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,33856,169,92,1966.0,0,0,36,0,0,87,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,59465,10,6,1962.0,0,0,0,5,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,28424,8,12,2001.0,0,7,0,4,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,63745,2,9,1965.0,2,0,0,1,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

checkpoint2

In [44]:
checkpoint2 = census.copy()

In [45]:
info = pd.DataFrame(index=census.columns.values,
                    data={'data type': census.dtypes, \
                          'non-null values': census.notnull().sum(),
                          'unique values': census.nunique(), \
                          'null values': census.isnull().sum()})
info.sort_values('non-null values').head(30)

,data type,non-null values,unique values,null values
pop_divorced,float64,0,0,33120
pop_separated,float64,0,0,33120
pop_now_married,float64,0,0,33120
pop_widowed,float64,0,0,33120
pop_never_married,float64,0,0,33120
pop_15_and_over,float64,0,0,33120
speak_spanish_at_home_low_english,float64,0,0,33120
speak_spanish_at_home,float64,0,0,33120
speak_only_english_at_home,float64,0,0,33120
pop_5_years_over,float64,0,0,33120
aggregate_travel_time_to_work,float64,20339,17086,12781
median_rent,float64,27217,1899,5903
renter_occupied_housing_units_paying_cash_median_gross_rent,float64,27373,1948,5747
percent_income_spent_on_rent,float64,27762,399,5358
owner_occupied_housing_units_lower_value_quartile,float64,30173,4221,2947
owner_occupied_housing_units_upper_value_quartile,float64,30704,6247,2416
owner_occupied_housing_units_median_value,float64,30774,5223,2346
median_income,float64,31112,19533,2008
median_year_structure_built,float64,32208,75,912
gini_index,float64,32254,4112,866
income_per_capita,float64,32515,20615,605
median_age,float64,32595,655,525
some_college_and_associates_degree,float64,32989,7533,131
population_1_year_and_over,float64,32989,15370,131
different_house_year_ago_different_city,float64,32989,4905,131
less_than_high_school_graduate,float64,32989,4555,131
graduate_professional_degree,float64,32989,4588,131
not_us_citizen_pop,float64,32989,4196,131
high_school_including_ged,float64,32989,7195,131
bachelors_degree_2,float64,32989,5991,131

Looking to see if any Medicare zip codes are missing from Census DF

In [49]:
census.geo_id = census.geo_id.astype('str').apply(lambda x: x.zfill(5))

In [50]:
med[med.full_zip.isin(census.geo_id)].shape, med[~med.full_zip.isin(census.geo_id)].shape

((1016368, 22), (31284, 22))

In [51]:
pd.options.display.max_rows = 120
med[
    ~med.full_zip.isin(census.geo_id)].head()

,npi,entity_code,full_zip,state,country,provider_type,medicare_participation_indicator,number_of_hcpcs,number_of_services,total_beneficiaries,...,total_medicare_payment,total_medicare_standardized_payment,avg_beneficiary_age,avg_hcc_risk_score,services_per_capita,allowed_payment_per_capita,medicare_payment_per_capita,submitted_charges_per_capita,region,subregion
9,1003031642,I,21287,MD,US,Certified Registered Nurse Anesthetist (CRNA),Y,30,86.0,84,...,12307.86,11784.47,71,1.9005,1.02,186.64,146.52,1561.71,South,South Atlantic
12,1003042854,I,21287,MD,US,Pathology,Y,9,727.0,365,...,21321.92,20583.77,73,1.6234,1.99,77.42,58.42,280.06,South,South Atlantic
15,1003066549,I,21287,MD,US,Physician Assistant,Y,25,321.0,246,...,24252.03,23230.93,64,1.5644,1.30,125.74,98.59,1002.00,South,South Atlantic
16,1003067414,I,20892,MD,US,Internal Medicine,Y,12,134.0,134,...,20488.35,18586.40,80,1.9749,1.00,201.03,152.90,420.63,South,South Atlantic
21,1003077587,I,20889,MD,US,Otolaryngology,Y,12,25.0,11,...,3703.96,3419.25,74,1.0875,2.27,438.26,336.72,1618.45,South,South Atlantic

##### Many are PO Boxes. Some are hospitals with their own zip codes. I want to drop these rows from Med, looking at how much of my data this will remove:

In [52]:
print(' Total providers in Med df:',med.shape[0],
     '\n Total beneficiaries in Med df:', med.total_beneficiaries.sum(),
     '\n Total providers whose zips not in Census:', 
                          med[~med.full_zip.isin(census.geo_id)].shape[0],
     '\n Total beneficiaries in Med in zips not in Census:', 
                          med[~med.full_zip.isin(census.geo_id)].total_beneficiaries.sum(),
     '\n Percent providers with missing zips of all providers:',
                          round(med[~med.full_zip.isin(census.geo_id)].shape[0] \
                          / med.shape[0] * 100, 2),  '%',
     '\n Percent beneficiaries in missing zips of all beneficiaries:',
                          round(med[~med.full_zip.isin(census.geo_id)].total_beneficiaries.sum() \
                          / med.total_beneficiaries.sum() * 100,2),  '%')

 Total providers in Med df: 1047652
 Total beneficiaries in Med df: 380997377
 Total providers whose zips not in Census: 31284
 Total beneficiaries in Med in zips not in Census: 10388923
 Percent providers with missing zips of all providers: 2.99 %
 Percent beneficiaries in missing zips of all beneficiaries: 2.73 %

In [53]:
idx = med[~med['full_zip'].isin(census.geo_id)].index
med.drop(index = idx, inplace=True)

Dropping Rows from Census that don't appear in Medicare DF

In [54]:
print(census.shape)
idx = census[~census.geo_id.isin(med.full_zip)].index
census.drop(index = idx, inplace = True)
print(census.shape)

(33120, 242)
(19560, 242)

In [55]:
med.full_zip.nunique()

19560

Examining Nulls

In [56]:
info = pd.DataFrame(index=census.columns.values,
                    data={'data type': census.dtypes, \
                          'non-null values': census.notnull().sum(),
                          'unique values': census.nunique(), \
                          'null values': census.isnull().sum()})
info.sort_values('non-null values').head(30)

,data type,non-null values,unique values,null values
aggregate_travel_time_to_work,float64,16488,14805,3072
median_rent,float64,18812,1850,748
renter_occupied_housing_units_paying_cash_median_gross_rent,float64,18847,1878,713
percent_income_spent_on_rent,float64,18926,387,634
owner_occupied_housing_units_lower_value_quartile,float64,19017,4020,543
owner_occupied_housing_units_upper_value_quartile,float64,19108,5664,452
owner_occupied_housing_units_median_value,float64,19109,4808,451
median_income,float64,19229,15590,331
median_year_structure_built,float64,19319,75,241
gini_index,float64,19333,2877,227
income_per_capita,float64,19483,14665,77
median_age,float64,19491,525,69
high_school_including_ged,float64,19508,7180,52
population_1_year_and_over,float64,19508,14452,52
different_house_year_ago_same_city,float64,19508,3585,52
graduate_professional_degree,float64,19508,4588,52
different_house_year_ago_different_city,float64,19508,4900,52
some_college_and_associates_degree,float64,19508,7513,52
not_us_citizen_pop,float64,19508,4184,52
bachelors_degree_2,float64,19508,5987,52
less_than_high_school_graduate,float64,19508,4542,52
white_male_55_64,int64,19560,2588,0
white_male_45_54,int64,19560,2720,0
hispanic_male_55_64,int64,19560,1165,0
bachelors_degree_or_higher_25_64,int64,19560,6956,0
children,int64,19560,8227,0
commuters_drove_alone,int64,19560,10128,0
commuters_by_bus,int64,19560,1659,0
commuters_by_car_truck_van,int64,19560,10591,0
commuters_by_carpool,int64,19560,2886,0

Sadly information about marriage and home language is totally missing.

In [57]:
info[info['non-null values']==0].index

Index([], dtype='object')

In [58]:
census.drop(columns = info[info['non-null values']==0].index, inplace=True)

Some of these columns are irrelevant or are redundant.

In [59]:
#there are other cols that speak to Commute to work
cols_to_drop = ['aggregate_travel_time_to_work','owner_occupied_housing_units_lower_value_quartile',
'owner_occupied_housing_units_median_value','owner_occupied_housing_units_upper_value_quartile',
'renter_occupied_housing_units_paying_cash_median_gross_rent','median_year_structure_built']

census.drop(columns = cols_to_drop, inplace = True)

In [60]:
info = pd.DataFrame(index=census.columns.values,
                    data={'data type': census.dtypes, \
                          'non-null values': census.notnull().sum(),
                          'unique values': census.nunique(), \
                          'null values': census.isnull().sum()})
info.sort_values('non-null values').head(30)

,data type,non-null values,unique values,null values
median_rent,float64,18812,1850,748
percent_income_spent_on_rent,float64,18926,387,634
median_income,float64,19229,15590,331
gini_index,float64,19333,2877,227
income_per_capita,float64,19483,14665,77
median_age,float64,19491,525,69
less_than_high_school_graduate,float64,19508,4542,52
bachelors_degree_2,float64,19508,5987,52
population_1_year_and_over,float64,19508,14452,52
some_college_and_associates_degree,float64,19508,7513,52
different_house_year_ago_different_city,float64,19508,4900,52
not_us_citizen_pop,float64,19508,4184,52
high_school_including_ged,float64,19508,7180,52
graduate_professional_degree,float64,19508,4588,52
different_house_year_ago_same_city,float64,19508,3585,52
commuters_drove_alone,int64,19560,10128,0
employed_information,int64,19560,1107,0
black_male_45_54,int64,19560,1249,0
black_male_55_64,int64,19560,1127,0
hispanic_male_45_54,int64,19560,1530,0
hispanic_male_55_64,int64,19560,1165,0
employed_finance_insurance_real_estate,int64,19560,2398,0
employed_education_health_social,int64,19560,5341,0
white_male_45_54,int64,19560,2720,0
white_male_55_64,int64,19560,2588,0
bachelors_degree_or_higher_25_64,int64,19560,6956,0
children,int64,19560,8227,0
children_in_single_female_hh,int64,19560,3809,0
commuters_by_bus,int64,19560,1659,0
commuters_by_car_truck_van,int64,19560,10591,0

In [61]:
# Let's look at rows in Medicare with zips that have nulls in Census.graduate_professional_degree
null_zips = census[census.graduate_professional_degree.isnull()].geo_id
med[med.full_zip.isin(null_zips)]

,npi,entity_code,full_zip,state,country,provider_type,medicare_participation_indicator,number_of_hcpcs,number_of_services,total_beneficiaries,...,total_medicare_payment,total_medicare_standardized_payment,avg_beneficiary_age,avg_hcc_risk_score,services_per_capita,allowed_payment_per_capita,medicare_payment_per_capita,submitted_charges_per_capita,region,subregion
47359,1588630495,I,00601,IL,US,Pulmonary Disease,Y,51,3399.0,1163,...,336334.64,319559.18,75,1.7296,2.92,381.77,289.20,883.40,Midwest,East North Central
47361,1588630552,I,00601,IL,US,Cardiovascular Disease (Cardiology),Y,46,2832.0,1157,...,199124.19,189357.22,78,1.6959,2.45,228.55,172.10,565.06,Midwest,East North Central
47366,1588631329,I,00601,IL,US,Psychiatry,Y,11,149.0,90,...,5375.25,5459.41,49,1.6478,1.66,96.82,59.72,242.73,Midwest,East North Central
47373,1588635411,I,00606,IL,US,Psychiatry,Y,11,1376.0,168,...,103767.14,101657.59,51,1.5409,8.19,798.50,617.66,1354.29,Midwest,East North Central
47384,1588641104,I,00606,IL,US,Interventional Radiology,Y,61,563.0,159,...,29002.73,28288.18,67,2.1677,3.54,243.42,182.41,3605.51,Midwest,East North Central
47385,1588641450,I,00601,IL,US,Radiation Oncology,Y,35,1994.0,263,...,120155.78,115814.84,73,1.9155,7.58,596.28,456.87,2999.29,Midwest,East North Central
47389,1588643449,I,00606,IL,US,Diagnostic Radiology,Y,61,1033.0,419,...,48934.91,50257.80,66,2.1511,2.47,162.74,116.79,1346.26,Midwest,East North Central
47391,1588643670,I,00601,IL,US,Pathology,Y,22,2698.0,799,...,88941.24,86230.52,70,1.8999,3.38,145.03,111.32,615.88,Midwest,East North Central
47392,1588644330,I,00601,IL,US,Emergency Medicine,Y,12,143.0,135,...,17749.87,16495.76,71,2.3072,1.06,175.61,131.48,792.84,Midwest,East North Central
47402,1588651566,I,00616,IL,US,Certified Registered Nurse Anesthetist (CRNA),Y,47,167.0,155,...,29930.54,30493.81,69,1.3779,1.08,248.38,193.10,1917.12,Midwest,East North Central
47458,1588691687,I,00617,IL,US,Emergency Medicine,Y,12,564.0,461,...,61924.60,62092.51,69,1.7785,1.22,176.69,134.33,531.47,Midwest,East North Central
47459,1588691877,I,00616,IL,US,Clinical Cardiatric Electrophysiology,Y,71,6256.0,2023,...,236086.74,242045.18,75,1.8823,3.09,161.53,116.70,679.17,Midwest,East North Central
47489,1588725758,I,00602,IL,US,Emergency Medicine,Y,29,601.0,546,...,71198.17,65729.62,78,1.9703,1.10,172.17,130.40,441.26,Midwest,East North Central
47501,1588743132,I,00606,IL,US,Optometry,Y,13,49.0,27,...,1760.56,1675.39,76,1.5839,1.81,163.38,65.21,184.82,Midwest,East North Central
47507,1588751135,I,00601,IL,US,Obstetrics & Gynecology,Y,20,94.0,67,...,6088.01,5905.15,70,0.5693,1.40,122.42,90.87,308.02,Midwest,East North Central
47518,1588757579,I,00617,IL,US,General Surgery,Y,64,454.0,176,...,63176.98,65790.00,73,1.0672,2.58,477.72,358.96,1484.09,Midwest,East North Central
47522,1588759005,I,00606,IL,US,Anesthesiology,Y,34,114.0,107,...,20027.93,18484.03,66,2.3440,1.07,244.89,187.18,1452.79,Midwest,East North Central
47523,1588759195,I,00603,IL,US,Psychiatry,Y,2,68.0,40,...,3386.79,3494.24,60,2.4773,1.70,110.20,84.67,221.44,Midwest,East North Central
47531,1588761811,I,00627,IL,US,Rheumatology,Y,45,33028.0,570,...,810263.03,818678.08,72,1.1557,57.94,1845.49,1421.51,2037.08,Midwest,East North Central
47569,1588795819,I,00606,IL,US,"Psychologist, Clinical",Y,5,457.0,36,...,11135.93,10576.30,63,1.5906,12.69,407.23,309.33,1810.86,Midwest,East North Central
47634,1588876510,I,00606,IL,US,Chiropractic,Y,2,495.0,55,...,14648.28,14628.39,71,1.0472,9.00,339.67,266.33,526.21,Midwest,East North Central
47652,1588918395,I,00606,IL,US,Family Practice,Y,20,847.0,305,...,66570.99,67737.69,72,2.4735,2.78,279.01,218.27,433.99,Midwest,East North Central
47675,1588954135,I,00603,IL,US,Physical Medicine and Rehabilitation,Y,23,625.0,329,...,42586.72,40766.68,73,2.6198,1.90,172.18,129.44,322.65,Midwest,East North Central
47680,1588957674,I,00606,IL,US,Dermatology,Y,15,67.0,22,...,3648.26,3402.60,77,1.3925,3.05,230.07,165.83,242.77,Midwest,East North Central
47683,1588963961,O,00622,IL,US,Ambulatory Surgical Center,Y,57,273.0,201,...,208426.97,216747.14,72,0.9773,1.36,1308.25,1036.95,7252.20,Midwest,East North Central
54804,1750491288,I,00617,IL,US,Podiatry,Y,35,1523.0,761,...,78585.88,73964.72,73,1.8951,2.00,137.89,103.27,227.95,Midwest,East North Central
249042,1588633028,I,00740,OK,US,Family Practice,Y,49,3139.0,475,...,93734.37,103116.82,75,1.2043,6.61,282.28,197.34,604.59,South,West South Central
249093,1588823074,I,00741,OK,US,Nurse Practitioner,Y,26,112.0,104,...,6749.04,7415.52,70,2.1313,1.08,90.13,64.89,861.30,South,West South Central
249101,1588858914,I,00741,OK,US,Pulmonary Disease,Y,23,1207.0,255,...,129745.57,136639.48,72,3.3500,4.73,669.02,508.81,1950.32,South,West South Central
303421,1588635684,I,00956,CA,US,Diagnostic Radiology,Y,196,5441.0,3564,...,123454.82,128493.95,73,1.4785,1.53,46.83,34.64,214.84,West,Pacific
303447,1588642805,I,00920,CA,US,Licensed Clinical Social Worker,Y,2,400.0,11,...,29702.14,29777.61,73,0.9763,36.36,3478.44,2700.19,4545.45,West,Pacific
303473,1588650675,I,00923,CA,US,Cardiovascular Disease (Cardiology),Y,61,21457.0,1429,...,818684.95,842983.00,75,1.9451,15.02,762.67,572.91,2017.23,West,Pacific
303476,1588656631,I,00949,CA,US,Obstetrics & Gynecology,Y,22,252.0,133,...,16716.01,16054.88,72,0.8594,1.89,181.64,125.68,295.93,West,Pacific
303481,1588654123,I,00926,CA,US,Family Practice,Y,51,613.0,84,...,21404.07,20171.46,74,1.0062,7.30,356.69,254.81,703.84,West,Pacific
303522,1588668065,I,00960,CA,US,Family Practice,Y,41,316.0,108,...,19311.42,19364.37,73,0.6901,2.93,210.64,178.81,307.74,West,Pacific
303646,1588697916,I,00920,CA,US,Thoracic Surgery,Y,13,71.0,42,...,23463.55,18532.14,67,2.2071,1.69,748.82,558.66,15735.93,West,Pacific
303661,1588704472,I,00956,CA,US,Emergency Medicine,Y,27,793.0,479,...,71287.80,70547.76,76,1.8545,1.66,191.93,148.83,690.81,West,Pacific
303662,1588704498,I,00956,CA,US,Emergency Medicine,Y,37,422.0,211,...,24506.25,24128.00,73,1.1016,2.00,165.32,116.14,285.03,West,Pacific
303674,1588709190,I,00912,CA,US,Optometry,Y,9,428.0,335,...,41224.65,38928.04,73,1.2441,1.28,161.97,123.06,181.48,West,Pacific
303701,1588718985,I,00953,CA,US,Chiropractic,Y,1,991.0,58,...,30907.91,30927.36,75,1.1421,17.09,703.27,532.90,768.88,West,Pacific
303714,1588725659,I,00917,CA,US,Obstetrics & Gynecology,Y,14,207.0,80,...,16521.90,16281.11,62,1.3929,2.59,265.09,206.52,434.62,West,Pacific
303775,1588750061,I,00917,CA,US,Ophthalmology,Y,17,853.0,280,...,54633.31,51014.30,77,1.2168,3.05,289.69,195.12,430.14,West,Pacific
303789,1588755466,I,00913,CA,US,Internal Medicine,Y,125,19213.0,468,...,330374.40,321722.64,75,1.0052,41.05,879.46,705.93,2215.62,West,Pacific
303795,1588757074,I,00915,CA,US,Diagnostic Radiology,Y,73,1017.0,314,...,196405.34,171687.57,73,1.2043,3.24,801.35,625.49,2141.24,West,Pacific
303852,1588776033,I,00921,CA,US,Chiropractic,Y,1,655.0,47,...,20343.21,19542.71,74,1.0420,13.94,597.30,432.83,1045.21,West,Pacific
303880,1588789788,I,00936,CA,US,Family Practice,Y,39,8719.0,272,...,70010.55,69313.76,71,0.8379,32.06,369.13,257.39,599.43,West,Pacific
303928,1588826382,I,00913,CA,US,Surgical Oncology,Y,14,28.0,17,...,13696.52,12196.60,73,1.5678,1.65,1030.13,805.68,5950.22,West,Pacific
304007,1588877906,I,00926,CA,US,Licensed Clinical Social Worker,Y,4,839.0,59,...,59618.42,57625.70,63,1.1058,14.22,1366.29,1010.48,2568.14,West,Pacific
304013,1588891071,I,00907,CA,US,Podiatry,Y,39,1732.0,470,...,84685.34,75851.66,80,1.4992,3.69,232.18,180.18,243.94,West,Pacific
304058,1588938286,I,00953,CA,US,Oral Surgery (Dentists only),Y,3,16.0,14,...,1330.59,1293.82,75,2.5315,1.14,121.23,95.04,326.43,West,Pacific
304092,1588975247,I,00913,CA,US,"Psychologist, Clinical",Y,4,554.0,57,...,57588.30,54469.01,85,2.8928,9.72,1294.55,1010.32,1475.88,West,Pacific
304097,1588977847,I,00912,CA,US,Optometry,Y,13,365.0,173,...,19534.82,18855.66,75,0.9254,2.11,169.68,112.92,208.24,West,Pacific
378158,1588660047,I,00782,TX,US,Family Practice,Y,33,231.0,79,...,5052.56,5751.82,75,0.8612,2.92,95.60,63.96,115.22,South,West South Central
378191,1588667778,I,00773,TX,US,Physical Medicine and Rehabilitation,Y,15,6471.0,629,...,352533.16,358712.23,72,3.2801,10.29,720.00,560.47,1213.74,South,West South Central
378202,1588670731,I,00784,TX,US,Emergency Medicine,Y,15,120.0,77,...,9708.97,9985.93,71,3.5301,1.56,169.91,126.09,1678.55,South,West South Central
378208,1588671853,I,00780,TX,US,Family Practice,Y,32,3705.0,370,...,157779.07,174935.27,72,1.5325,10.01,598.39,426.43,923.99,South,West South Central
378214,1588674246,I,00754,TX,US,Certified Registered Nurse Anesthetist (CRNA),Y,10,222.0,216,...,11799.97,12527.49,71,1.1587,1.03,69.05,54.63,527.11,South,West South Central
378276,1588695423,I,00757,TX,US,Family Practice,Y,19,10676.0,1762,...,606779.39,658482.87,77,2.4890,6.06,465.04,344.37,657.52,South,West South Central
378346,1588753412,I,00751,TX,US,Psychiatry,Y,3,113.0,13,...,2703.74,3010.48,45,0.9886,8.69,321.75,207.98,335.06,South,West South Central
378347,1588753586,I,00751,TX,US,Psychiatry,Y,3,44.0,13,...,1070.49,1213.09,71,1.7469,3.38,151.38,82.35,157.63,South,West South Central
378354,1588757462,I,00773,TX,US,Neurology,Y,29,2246.0,415,...,179240.39,197832.03,69,1.3426,5.41,603.29,431.90,1746.80,South,West South Central
378399,1588786446,I,00782,TX,US,Family Practice,Y,35,141.0,65,...,3681.75,4261.29,75,0.9099,2.17,89.27,56.64,110.18,South,West South Central
378420,1588811731,I,00777,TX,US,Family Practice,Y,3,57.0,53,...,1767.78,1823.65,62,1.1538,1.08,55.92,33.35,157.43,South,West South Central
378437,1588824577,I,00775,TX,US,General Practice,Y,14,299.0,53,...,11874.77,12041.98,78,2.1647,5.64,287.83,224.05,817.87,South,West South Central
378440,1588825962,I,00765,TX,US,Hematology-Oncology,Y,18,1151.0,455,...,70689.09,73838.93,70,2.0842,2.53,212.61,155.36,542.82,South,West South Central
378480,1588857874,I,00782,TX,US,Hand Surgery,Y,37,146.0,34,...,15488.38,16536.45,71,0.9856,4.29,599.44,455.54,11147.32,South,West South Central
378486,1588863898,I,00765,TX,US,Interventional Cardiology,Y,88,3961.0,1433,...,212422.46,226566.43,73,1.7835,2.76,198.63,148.24,1431.64,South,West South Central
378572,1588955546,I,00791,TX,US,Internal Medicine,Y,14,987.0,480,...,85440.33,88478.87,74,2.6612,2.06,227.67,178.00,725.94,South,West South Central
468655,1588681241,I,00631,MO,US,Diagnostic Radiology,Y,133,4801.0,2328,...,116848.17,119942.69,73,1.4609,2.06,61.10,50.19,150.39,Midwest,West North Central
468691,1588751382,I,00631,MO,US,Pulmonary Disease,Y,25,822.0,360,...,85211.31,83668.80,71,3.0072,2.28,311.84,236.70,816.65,Midwest,West North Central
468692,1588752364,I,00652,MO,US,Psychiatry,Y,12,1614.0,589,...,85779.24,94599.32,58,1.4659,2.74,208.99,145.64,349.16,Midwest,West North Central
468697,1588759625,I,00656,MO,US,Nurse Practitioner,Y,13,597.0,136,...,36152.15,39077.26,71,1.6120,4.39,356.30,265.82,719.36,Midwest,West North Central
468705,1588765549,I,00641,MO,US,Certified Registered Nurse Anesthetist (CRNA),Y,46,140.0,140,...,35146.78,36073.10,72,1.9330,1.00,319.95,251.05,373.83,Midwest,West North Central
468710,1588775241,I,00631,MO,US,Dermatology,Y,37,3182.0,1071,...,142700.86,156959.51,74,0.9447,2.97,197.12,133.24,206.24,Midwest,West North Central
468733,1588862544,I,00631,MO,US,Internal Medicine,Y,33,2123.0,536,...,152169.43,140671.74,74,1.0915,3.96,322.05,283.90,522.36,Midwest,West North Central
659150,1588627533,I,00704,LA,US,Interventional Cardiology,Y,104,3961.0,1605,...,188655.44,193087.52,73,2.0683,2.47,155.55,117.54,561.09,South,West South Central
659165,1588657878,I,00703,LA,US,Family Practice,Y,112,5716.0,754,...,141382.36,152405.20,72,1.1595,7.58,259.97,187.51,417.36,South,West South Central
659237,1588869309,I,00705,LA,US,Obstetrics & Gynecology,Y,7,50.0,47,...,2720.15,2915.09,69,0.6218,1.06,63.19,57.88,198.62,South,West South Central
659240,1588906317,I,00705,LA,US,Physician Assistant,Y,57,507.0,221,...,16568.13,17245.89,64,1.2482,2.29,109.21,74.97,828.35,South,West South Central
737568,1588737787,I,00983,WA,US,Chiropractic,Y,2,205.0,31,...,5474.39,5769.52,74,0.9488,6.61,259.77,176.59,461.77,West,Pacific
737574,1588743108,I,00982,WA,US,Physical Therapist in Private Practice,Y,12,1052.0,43,...,21415.02,23412.51,71,0.8311,24.47,687.34,498.02,1497.53,West,Pacific
737643,1588871974,I,00982,WA,US,Family Practice,Y,44,428.0,147,...,27163.06,26041.34,75,0.9812,2.91,271.47,184.78,580.35,West,Pacific
737670,1588957161,O,00983,WA,US,Clinical Laboratory,Y,29,13521.0,1503,...,144070.55,147580.83,72,0.7874,9.00,98.32,95.86,242.37,West,Pacific
923615,1588764583,I,00688,NE,US,Certified Registered Nurse Anesthetist (CRNA),Y,3,13.0,13,...,2404.01,2602.10,79,1.3365,1.00,235.87,184.92,1187.04,Midwest,West North Central
973688,1588657324,I,00670,KS,US,Certified Registered Nurse Anesthetist (CRNA),Y,14,93.0,86,...,9553.23,10089.12,74,1.9018,1.08,140.06,111.08,880.00,Midwest,West North Central
973689,1588657357,I,00678,KS,US,Chiropractic,Y,2,464.0,102,...,12351.90,13564.36,74,0.8474,4.55,171.31,121.10,181.96,Midwest,West North Central
973712,1588716963,I,00667,KS,US,"Psychologist, Clinical",Y,6,318.0,54,...,24634.21,27383.26,58,1.5072,5.89,613.48,456.19,733.96,Midwest,West North Central
973713,1588725261,I,00667,KS,US,Optometry,Y,6,282.0,262,...,10344.50,26123.61,73,1.0927,1.08,68.05,39.48,75.77,Midwest,West North Central
973726,1588767164,I,00667,KS,US,General Practice,Y,53,8088.0,599,...,184007.55,209364.92,70,1.3450,13.50,440.52,307.19,548.98,Midwest,West North Central
973760,1588971378,I,00667,KS,US,Nurse Practitioner,Y,8,364.0,314,...,9917.85,10674.64,73,1.5005,1.16,47.50,31.59,163.82,Midwest,West North Central
979212,1205990884,I,00683,RI,US,Anesthesiology,Y,37,237.0,186,...,67818.22,76041.68,71,2.9610,1.27,468.17,364.61,477.95,Northeast,New England
1016150,1588643563,I,00720,AR,US,Dermatology,Y,45,6394.0,1633,...,189393.63,227733.22,75,1.0045,3.92,172.34,115.98,196.69,South,West South Central
1016188,1588773410,I,00720,AR,US,Licensed Clinical Social Worker,Y,3,68.0,16,...,3504.72,3699.62,50,0.9896,4.25,287.58,219.04,537.75,South,West South Central
1016192,1588802987,O,00719,AR,US,Ambulatory Surgical Center,Y,18,2100.0,1144,...,564775.94,614978.97,70,0.8279,1.84,639.67,493.69,2202.45,South,West South Central
1016205,1588892822,I,00727,AR,US,Physical Therapist in Private Practice,Y,11,5158.0,104,...,88359.30,96972.74,77,1.2193,49.60,1102.50,849.61,2058.32,South,West South Central

In [40]:
# These zip codes are mismatched with their NPIs. It's likely that they got caught up in 
med.loc[
    med[med.npi == '1750491288'].index, 'full_zip'] = '60617'

#Droppping other two rows from DF
null_zips = census[census.graduate_professional_degree.isnull()].geo_id
idx = med[med.full_zip.isin(null_zips)].index
med.drop(index = idx, inplace=True)

In [41]:
#Dropping these zips from Census 
census = census[census.graduate_professional_degree.notnull()]

##### REEXAMINING CENSUS NULLS

In [42]:
info = pd.DataFrame(index=census.columns.values,
                    data={'data type': census.dtypes, \
                          'non-null values': census.notnull().sum(),
                          'unique values': census.nunique(), \
                          'null values': census.isnull().sum()})
info.sort_values('non-null values').head(30)

,data type,non-null values,unique values,null values
median_rent,float64,18699,1796,707
percent_income_spent_on_rent,float64,18813,388,593
median_income,float64,19075,15421,331
gini_index,float64,19183,2833,223
income_per_capita,float64,19330,14492,76
median_age,float64,19341,518,65
employed_retail_trade,int64,19406,3289,0
white_male_45_54,int64,19406,2753,0
employed_wholesale_trade,int64,19406,1190,0
white_male_55_64,int64,19406,2587,0
bachelors_degree_2,float64,19406,5959,0
bachelors_degree_or_higher_25_64,int64,19406,6910,0
children,int64,19406,8188,0
children_in_single_female_hh,int64,19406,3838,0
commuters_by_bus,int64,19406,1656,0
commuters_by_car_truck_van,int64,19406,10479,0
commuters_by_carpool,int64,19406,2865,0
commuters_by_subway_or_elevated,int64,19406,895,0
commuters_drove_alone,int64,19406,9985,0
employed_transportation_warehousing_utilities,int64,19406,1847,0
different_house_year_ago_same_city,float64,19406,3615,0
employed_agriculture_forestry_fishing_hunting_mining,int64,19406,1008,0
employed_arts_entertainment_recreation_accommodation_food,int64,19406,3041,0
employed_construction,int64,19406,2088,0
employed_education_health_social,int64,19406,5272,0
employed_finance_insurance_real_estate,int64,19406,2395,0
employed_information,int64,19406,1109,0
employed_manufacturing,int64,19406,3059,0
employed_other_services_not_public_admin,int64,19406,1765,0
employed_public_administration,int64,19406,1853,0

The remaining columns with nulls are important, but I know that other columns in the DF, have some information related to rent, income, and age.

In [43]:
census.columns[census.columns.str.contains('_rent$|^rent_|_rent_', regex=True)]

Index(['rent_burden_not_computed', 'rent_over_50_percent',
       'rent_40_to_50_percent', 'rent_35_to_40_percent',
       'rent_30_to_35_percent', 'rent_25_to_30_percent',
       'rent_20_to_25_percent', 'rent_15_to_20_percent',
       'rent_10_to_15_percent', 'rent_under_10_percent',
       'vacant_housing_units_for_rent', 'median_rent',
       'percent_income_spent_on_rent'],
      dtype='object')

In [44]:
census.columns[census.columns.str.contains('income')]

Index(['median_income', 'income_per_capita', 'percent_income_spent_on_rent',
       'income_less_10000', 'income_10000_14999', 'income_15000_19999',
       'income_20000_24999', 'income_25000_29999', 'income_30000_34999',
       'income_35000_39999', 'income_40000_44999', 'income_45000_49999',
       'income_50000_59999', 'income_60000_74999', 'income_75000_99999',
       'income_100000_124999', 'income_125000_149999', 'income_150000_199999',
       'income_200000_or_more', 'households_retirement_income'],
      dtype='object')

In [45]:
census.columns[census.columns.str.contains('(?=.*male)(?=.*_to_)', regex=True)]

Index(['male_5_to_9', 'male_10_to_14', 'male_15_to_17', 'male_18_to_19',
       'male_22_to_24', 'male_25_to_29', 'male_30_to_34', 'male_35_to_39',
       'male_40_to_44', 'male_45_to_49', 'male_50_to_54', 'male_55_to_59',
       'male_65_to_66', 'male_67_to_69', 'male_70_to_74', 'male_75_to_79',
       'male_80_to_84', 'female_5_to_9', 'female_10_to_14', 'female_15_to_17',
       'female_18_to_19', 'female_22_to_24', 'female_25_to_29',
       'female_30_to_34', 'female_35_to_39', 'female_40_to_44',
       'female_45_to_49', 'female_50_to_54', 'female_55_to_59',
       'female_60_to_61', 'female_62_to_64', 'female_65_to_66',
       'female_67_to_69', 'female_70_to_74', 'female_75_to_79',
       'female_80_to_84', 'male_45_to_64'],
      dtype='object')

In [46]:
info[info['null values']>0].index

Index(['median_age', 'median_income', 'income_per_capita', 'median_rent',
       'percent_income_spent_on_rent', 'gini_index'],
      dtype='object')

While these factors are probably very relevant to the number of providers in a zip code, the health risk score, and the use of different providers, it seems there are other features in Census DF that may also address income, rent, and age.

In [47]:
#dropping these cols with nulls
cols = info[info['null values']>0].index
census.drop(columns = cols, inplace=True)

# Checking Data Types

All columns in Census besides Geo_id should be 'int' or 'float.' I want to see what is listed as object.

In [48]:
census.select_dtypes('object').head(1)

  geo_id
4  37228

There's a column called do_date that includes the years used to make the estimate Census measures. I'm going to keep that last four digits which represent the year being estimated.

In [49]:
census.do_date = census.do_date.apply(lambda x: str(x)[-4:])
census.do_date = pd.to_datetime(census.do_date, format='%Y')
census.do_date

4       2015-01-01
7       2015-01-01
10      2015-01-01
11      2015-01-01
17      2015-01-01
           ...
33114   2015-01-01
33115   2015-01-01
33117   2015-01-01
33118   2015-01-01
33119   2015-01-01
Name: do_date, Length: 19406, dtype: datetime64[ns]

In [50]:
census.isnull().sum().sort_values()

geo_id                              0
white_male_45_54                    0
white_male_55_64                    0
bachelors_degree_2                  0
bachelors_degree_or_higher_25_64    0
                                   ..
male_18_to_19                       0
male_20                             0
male_21                             0
dwellings_20_to_49_units            0
do_date                             0
Length: 234, dtype: int64

In [51]:
med.to_csv('../../data/processed/final2016MEDICARE.csv')
census.to_csv('../../data/processed/final2016CENSUS.csv')