In [1]:
import pandas as pd

In [39]:
chunks = pd.read_csv('/home/vizziwo/Medicare_Physician_and_Other_Supplier_National_Provider_Identifier__NPI__Aggregate_Report__Calendar_Year_2018.csv', chunksize=50000)

In [40]:
for chunk in chunks:
    df = chunk
    break

/opt/miniconda3/envs/cap2/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [41]:
df.head()

,National Provider Identifier,Last Name/Organization Name of the Provider,First Name of the Provider,Middle Initial of the Provider,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,Street Address 2 of the Provider,City of the Provider,...,Percent (%) of Beneficiaries Identified With Depression,Percent (%) of Beneficiaries Identified With Diabetes,Percent (%) of Beneficiaries Identified With Hyperlipidemia,Percent (%) of Beneficiaries Identified With Hypertension,Percent (%) of Beneficiaries Identified With Ischemic Heart Disease,Percent (%) of Beneficiaries Identified With Osteoporosis,Percent (%) of Beneficiaries Identified With Rheumatoid Arthritis / Osteoarthritis,Percent (%) of Beneficiaries Identified With Schizophrenia / Other Psychotic Disorders,Percent (%) of Beneficiaries Identified With Stroke,Average HCC Risk Score of Beneficiaries
0,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,47.0,53.0,75.0,75.0,55.0,11.0,56.0,9.0,11.0,2.2948
1,1003000134,CIBULL,THOMAS,L,M.D.,M,I,2650 RIDGE AVE,EVANSTON HOSPITAL,EVANSTON,...,15.0,20.0,51.0,53.0,27.0,10.0,39.0,1.0,3.0,1.0899
2,1003000142,KHALIL,RASHID,NaN,M.D.,M,I,4126 N HOLLAND SYLVANIA RD,SUITE 220,TOLEDO,...,44.0,31.0,51.0,68.0,35.0,5.0,75.0,6.0,5.0,1.7085
3,1003000407,GIRARDI,DAVID,J,D.O.,M,I,100 HOSPITAL RD,NaN,BROOKVILLE,...,53.0,39.0,67.0,75.0,57.0,21.0,46.0,15.0,9.0,2.1838
4,1003000423,VELOTTA,JENNIFER,A,M.D.,F,I,11100 EUCLID AVE,NaN,CLEVELAND,...,23.0,23.0,49.0,56.0,21.0,NaN,41.0,NaN,NaN,1.0221

In [42]:
df.columns

Index(['National Provider Identifier',
       'Last Name/Organization Name of the Provider',
       'First Name of the Provider', 'Middle Initial of the Provider',
       'Credentials of the Provider', 'Gender of the Provider',
       'Entity Type of the Provider', 'Street Address 1 of the Provider',
       'Street Address 2 of the Provider', 'City of the Provider',
       'Zip Code of the Provider', 'Provider RUCA',
       'State Code of the Provider', 'Country Code of the Provider',
       'Provider Type of the Provider', 'Medicare Participation Indicator',
       'Number of HCPCS', 'Number of Services',
       'Number of Medicare Beneficiaries', 'Total Submitted Charge Amount',
       'Total Medicare Allowed Amount', 'Total Medicare Payment Amount',
       'Total Medicare Standardized Payment Amount', 'Drug Suppress Indicator',
       'Number of HCPCS Associated With Drug Services',
       'Number of Drug Services',
       'Number of Medicare Beneficiaries With Drug Services',
       'Total Drug Submitted Charge Amount',
       'Total Drug Medicare Allowed Amount',
       'Total Drug Medicare Payment Amount',
       'Total Drug Medicare Standardized Payment Amount',
       'Medical Suppress Indicator',
       'Number of HCPCS Associated With Medical Services',
       'Number of Medical Services',
       'Number of Medicare Beneficiaries With Medical Services',
       'Total Medical Submitted Charge Amount',
       'Total Medical Medicare Allowed Amount',
       'Total Medical Medicare Payment Amount',
       'Total Medical Medicare Standardized Payment Amount',
       'Average Age of Beneficiaries', 'Number of Beneficiaries Age Less 65',
       'Number of Beneficiaries Age 65 to 74',
       'Number of Beneficiaries Age 75 to 84',
       'Number of Beneficiaries Age Greater 84',
       'Number of Female Beneficiaries', 'Number of Male Beneficiaries',
       'Number of Non-Hispanic White Beneficiaries',
       'Number of Black or African American Beneficiaries',
       'Number of Asian Pacific Islander Beneficiaries',
       'Number of Hispanic Beneficiaries',
       'Number of American Indian/Alaska Native Beneficiaries',
       'Number of Beneficiaries With Race Not Elsewhere Classified',
       'Number of Beneficiaries With Medicare Only Entitlement',
       'Number of Beneficiaries With Medicare & Medicaid Entitlement',
       'Percent (%) of Beneficiaries Identified With Atrial Fibrillation',
       'Percent (%) of Beneficiaries Identified With Alzheimerâ€™s Disease or Dementia',
       'Percent (%) of Beneficiaries Identified With Asthma',
       'Percent (%) of Beneficiaries Identified With Cancer',
       'Percent (%) of Beneficiaries Identified With Heart Failure',
       'Percent (%) of Beneficiaries Identified With Chronic Kidney Disease',
       'Percent (%) of Beneficiaries Identified With Chronic Obstructive Pulmonary Disease',
       'Percent (%) of Beneficiaries Identified With Depression',
       'Percent (%) of Beneficiaries Identified With Diabetes',
       'Percent (%) of Beneficiaries Identified With Hyperlipidemia',
       'Percent (%) of Beneficiaries Identified With Hypertension',
       'Percent (%) of Beneficiaries Identified With Ischemic Heart Disease',
       'Percent (%) of Beneficiaries Identified With Osteoporosis',
       'Percent (%) of Beneficiaries Identified With Rheumatoid Arthritis / Osteoarthritis',
       'Percent (%) of Beneficiaries Identified With Schizophrenia / Other Psychotic Disorders',
       'Percent (%) of Beneficiaries Identified With Stroke',
       'Average HCC Risk Score of Beneficiaries'],
      dtype='object')

In [43]:
df['Provider Type of the Provider'].unique()

array(['Internal Medicine', 'Pathology', 'Anesthesiology',
       'Family Practice', 'Obstetrics & Gynecology', 'General Surgery',
       'Urology', 'Cardiac Surgery', 'Physician Assistant',
       'Licensed Clinical Social Worker',
       'Physical Therapist in Private Practice',
       'Certified Registered Nurse Anesthetist (CRNA)', 'Optometry',
       'Mass Immunizer Roster Biller',
       'Physical Medicine and Rehabilitation', 'Radiation Oncology',
       'Infectious Disease', 'Nurse Practitioner', 'Orthopedic Surgery',
       'Endocrinology', 'Chiropractic', 'Psychiatry',
       'Diagnostic Radiology', 'Centralized Flu', 'Rheumatology',
       'General Practice', 'Neurology', 'Emergency Medicine',
       'Dermatology', 'Nephrology', 'Pediatric Medicine',
       'Pulmonary Disease', 'Otolaryngology',
       'Plastic and Reconstructive Surgery', 'Psychologist, Clinical',
       'Cardiology', 'Ambulance Service Provider', 'Ophthalmology',
       'Interventional Cardiology', 'Gastroenterology', 'Hospitalist',
       'Audiologist', 'Geriatric Medicine', 'Neurosurgery',
       'Interventional Radiology', 'Critical Care (Intensivists)',
       'Podiatry', 'Hematology-Oncology', 'Pharmacy',
       'Ambulatory Surgical Center',
       'Certified Clinical Nurse Specialist', 'Medical Oncology',
       'Nuclear Medicine', 'Occupational Therapist in Private Practice',
       'Thoracic Surgery', 'Allergy/ Immunology',
       'Certified Nurse Midwife', 'Pain Management', 'Sports Medicine',
       'Hand Surgery', 'Hospice and Palliative Care',
       'Independent Diagnostic Testing Facility (IDTF)',
       'Speech Language Pathologist', 'Clinical Laboratory',
       'Advanced Heart Failure and Transplant Cardiology',
       'Osteopathic Manipulative Medicine',
       'Registered Dietitian or Nutrition Professional',
       'Vascular Surgery', 'Anesthesiology Assistant',
       'Clinical Cardiac Electrophysiology', 'Addiction Medicine',
       'Oral Surgery (Dentist only)', 'Undefined Physician type',
       'Hematology', 'Maxillofacial Surgery', 'Portable X-Ray Supplier',
       'Colorectal Surgery (Proctology)', 'Mammography Center',
       'Surgical Oncology', 'Gynecological Oncology',
       'Interventional Pain Management', 'Preventive Medicine',
       'All Other Suppliers',
       'Hematopoietic Cell Transplantation and Cellular Therapy',
       'Public Health or Welfare Agency', 'Sleep Medicine',
       'Neuropsychiatry', 'Peripheral Vascular Disease',
       'Clinic or Group Practice', 'Radiation Therapy Center',
       'Geriatric Psychiatry', 'Dentist'], dtype=object)

In [50]:
df[df['Provider Type of the Provider']=='Psychologist, Clinical']

,National Provider Identifier,Last Name/Organization Name of the Provider,First Name of the Provider,Middle Initial of the Provider,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,Street Address 2 of the Provider,City of the Provider,...,Percent (%) of Beneficiaries Identified With Depression,Percent (%) of Beneficiaries Identified With Diabetes,Percent (%) of Beneficiaries Identified With Hyperlipidemia,Percent (%) of Beneficiaries Identified With Hypertension,Percent (%) of Beneficiaries Identified With Ischemic Heart Disease,Percent (%) of Beneficiaries Identified With Osteoporosis,Percent (%) of Beneficiaries Identified With Rheumatoid Arthritis / Osteoarthritis,Percent (%) of Beneficiaries Identified With Schizophrenia / Other Psychotic Disorders,Percent (%) of Beneficiaries Identified With Stroke,Average HCC Risk Score of Beneficiaries
72,1003005430,BEAUMONT,LAURA,A,PSYD,F,I,11801 SOUTHWEST HIGHWAY,STE 3 SOUTH,PALOS HEIGHTS,...,74.0,NaN,NaN,58.0,NaN,NaN,NaN,NaN,0.0,0.8026
236,1003013574,LADANYE,KAREN,R,PH.D.,F,I,125 BANK ST,SUITE 310,MISSOULA,...,69.0,34.0,53.0,59.0,NaN,NaN,44.0,NaN,NaN,1.4575
584,1003034570,BURGHER,PETER,L,PH.D,M,I,2 ELM ST,NaN,WATERVILLE,...,75.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,2.2817
619,1003037441,ZAPLAC,TRUDI,NaN,PH.D.,F,I,2003 PATTERSON DR,NaN,VICTORIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.6789
649,1003039785,YOUNG,DAVID,M,PH.D.,M,I,608 FLORAL VALE BLVD,NaN,YARDLEY,...,75.0,67.0,71.0,75.0,45.0,NaN,39.0,69.0,27.0,3.3313
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49671,1043320500,SHEIN,SAMUEL,T,PHD,M,I,757 TEANECK ROAD,NaN,TEANECK,...,75.0,NaN,52.0,59.0,NaN,NaN,44.0,NaN,NaN,0.9267
49690,1043321268,FIELDS,ROBERT,B,PHD,M,I,105 BRAUNLICH DR SUITE 480,NaN,PITTSBURGH,...,75.0,NaN,47.0,57.0,35.0,NaN,65.0,NaN,NaN,1.3802
49736,1043322829,DURKA,DAVID,W,PHD,M,I,DR D DURKA 3201 HIGHFIELD DR SUITE H BETHLEHEM...,NaN,BETHLEHEM,...,72.0,0.0,NaN,67.0,NaN,NaN,NaN,0.0,0.0,1.1757
49764,1043323751,DORFMAN,WILLIAM,I,PH.D.,M,I,224 COMMERCIAL BLVD,#303,LAUDERDALE BY THE SEA,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.6745
49839,1043326135,BROWN,NATALIE,L,PHD,F,I,526 EAST BROAD STREET,NaN,WESTFIELD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.8535

In [48]:
df[df['Provider Type of the Provider']=='Psychiatry'].iloc[:, 1:16]

,Last Name/Organization Name of the Provider,First Name of the Provider,Middle Initial of the Provider,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,Street Address 2 of the Provider,City of the Provider,Zip Code of the Provider,Provider RUCA,State Code of the Provider,Country Code of the Provider,Provider Type of the Provider,Medicare Participation Indicator
35,CASTRO CORDOBA,JUAN LUIS,NaN,NaN,M,I,2640 FOREST HILL BLVD,NaN,WEST PALM BEACH,33406,1.0,FL,US,Psychiatry,Y
90,GVOZDJAN,DRAGOSLAV,NaN,M.D.,M,I,415 N 26TH ST STE 103,NaN,LAFAYETTE,47904,1.0,IN,US,Psychiatry,Y
102,HARLOW,MICHAEL,C,M.D.,M,I,900 S 8TH ST STE 110,HENNEPIN COUNTY MEDICAL CENTER,MINNEAPOLIS,55404,1.0,MN,US,Psychiatry,Y
206,SOLIMAN,MAGED,S,M.D.,M,I,CHILD AND ADOLESCENT PSYCHIATRY OUTPATIENT DEP...,169 PUTNAM HALL,STONY BROOK,11794,1.0,NY,US,Psychiatry,Y
212,LU,DUNYUE,NaN,M.D.,M,I,401 S BALLENGER HWY,NaN,FLINT,48532,1.0,MI,US,Psychiatry,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49881,RASTOGI,SANTOSH,K,MD,M,I,27351 DEQUINDRE RD,NaN,MADISON HEIGHTS,48071,1.0,MI,US,Psychiatry,Y
49951,FAMY,CHRISTOPHER,S,MD,M,I,1600 E JEFFERSON ST,STE 401,SEATTLE,98122,1.0,WA,US,Psychiatry,Y
49957,WHITE,CLARENCE,G,M.D.,M,I,301 PROSPECT AVE,CPEP,SYRACUSE,13203,1.0,NY,US,Psychiatry,Y
49970,BURKY,CHRISTOPHER,S,MD,M,I,31 LAFAYETTE ST,NaN,SCHENECTADY,12305,1.0,NY,US,Psychiatry,Y
49971,BAYLES,S. TYLER,NaN,MD,M,I,5918 LEE AVE,NaN,LITTLE ROCK,72205,1.0,AR,US,Psychiatry,Y

In [51]:
x = 1
for chunk in chunks:
    x += 1

/opt/miniconda3/envs/cap2/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [52]:
x

23

In [54]:
23*50000

1150000

In [60]:
df['Pct_Black'] = df['Number of Black or African American Beneficiaries'] / df['Number of Medicare Beneficiaries'] * 100

In [82]:
y = df[(df['Provider Type of the Provider']=='Psychiatry') | (df['Provider Type of the Provider']=='Psychologist, Clinical') | (df['Provider Type of the Provider']=='Licensed Clinical Social Worker')]

In [83]:
len(y)

2671

In [84]:
y.groupby('Zip Code of the Provider').Pct_Black.mean().value_counts().reset_index().sort_values('Pct_Black', ascending=False)

         index  Pct_Black
0     0.000000        309
1    50.000000          5
2    53.125000          2
3    25.490196          2
4    55.263158          2
..         ...        ...
93   15.000000          1
94   46.000000          1
95   40.000000          1
96   12.500000          1
253  64.876033          1

[254 rows x 2 columns]